### ISSUE TITLE
Prevents vscode from displaying type validation errors when active

### ISSUE THREAD

**Issue by Claudiohbsantos** [TypeScriptToLua/vscode-typescript-to-lua#1]
Issue originally reported on TypescriptToLua. See https://github.com/TypeScriptToLua/TypeScriptToLua/issues/900 for more information.

extension version tested: 0.1.0

current fix: Uninstalled the extension

**Comment by Dragoteryx** [comment]
Can confirm, this bug is happening to me as well.
Uninstalling the extension fixes it.
