### ISSUE TITLE
Update the json-schema for `tsconfig.json` with TSTL

### ISSUE THREAD

**Issue by Toliak** [TypeScriptToLua/vscode-typescript-to-lua#4]
**Description**
I'm very frustrated when I'm trying to setup `tstl` section in `tsconfig.json` and my IDE hints me nothing.

I would like to suggest to provide the json-schema for `tsconfig.json` with `tstl` section.

**The solution**
I have already made the described json-schema :)

To use it insert
```json
"$schema": "https://raw.githubusercontent.com/mtasa-typescript/mtasa-lua-utils/feature/toolchain/tstl-tsconfig.schema.json"
```
at the top of your `tsconfig.json` file.

**Some screenshots**

In VSCode:
![image](https://user-images.githubusercontent.com/25643405/129780947-c054dee4-74cd-46a8-8ac8-00146a425995.png)

In WebStorm:
![image](https://user-images.githubusercontent.com/25643405/129781006-b3d4cbb0-c33c-4264-8a16-275068d9db54.png)

Are you interested in this feature? If the answer is positive, I could create Merge Request  with the schema file (just let me know, where to place it)

**Comment by Toliak** [comment]
About auto-generating schema: the first google result redirects me to the [typescript-json-schema package](https://github.com/YousefED/typescript-json-schema).

However, I'm not fully understood, how the pipeline will look like. In my head it's something like:
1. On commit into master branch of the typescript-to-lua: github action (or something else) generates the updated schema
2. The updated schema is being commited (or Merge Requested) into this repo (vscode-typescript-to-lua)

<hr>

Maybe mention the schema somewhere in documentation, because, when I searched, I haven't find anything :c 
![image](https://user-images.githubusercontent.com/25643405/129784400-67dfec97-93e9-4062-a0de-5bc4415238b3.png)
![image](https://user-images.githubusercontent.com/25643405/129784528-a0035700-9712-4734-99f5-b6e2587824f5.png)

<hr>

I will make the Merge Request with manually changed schema in a few minutes

**Comment by lolleko** [comment]
> About auto-generating schema: the first google result redirects me to the [typescript-json-schema package](https://github.com/YousefED/typescript-json-schema).
> 
> However, I'm not fully understood, how the pipeline will look like. In my head it's something like:
> 
> 1. On commit into master branch of the typescript-to-lua: github action (or something else) generates the updated schema
> 2. The updated schema is being commited (or Merge Requested) into this repo (vscode-typescript-to-lua)

Auto-generating is not a priority, I just thought it would be cool. So, that's something we might want to look in the future, but a manual schema is totally fine for now.
Also, not sure if the schema should be part of the main repo or if we should just keep it in the vscode plugin.

> Maybe mention the schema somewhere in documentation, because, when I searched, I haven't find anything :c

To be honest I didn't even know the vscode plugin had this capability until 5min ago :D
Please don't hesitate to open another PR for the website(https://typescripttolua.github.io/docs/configuration) that links the updated schema from this repo.
